### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/impact-graph#1078]
From the logs (mainnet-production):
```
TypeError: t[0].involvesToken is not a function
    at new t (/usr/src/app/node_modules/@uniswap/sdk/dist/sdk.cjs.production.min.js:1:15658)
    at SdkV2.getPrice (/usr/src/app/node_modules/@giveth/monoswap/dist/src/sdk/sdkV2.js:82:23)
    at SdkV2.<anonymous> (/usr/src/app/node_modules/@giveth/monoswap/dist/src/sdk/sdkV2.js:150:33)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/@giveth/monoswap/dist/src/sdk/sdkV2.js:28:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by geleeroyale** [comment]
TypeError: t[0].involvesToken is not a function
    at new t (/usr/src/app/node_modules/@uniswap/sdk/dist/sdk.cjs.production.min.js:1:15658)
    at SdkV2.getPrice (/usr/src/app/node_modules/@giveth/monoswap/dist/src/sdk/sdkV2.js:82:23)
    at SdkV2.<anonymous> (/usr/src/app/node_modules/@giveth/monoswap/dist/src/sdk/sdkV2.js:150:33)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/@giveth/monoswap/dist/src/sdk/sdkV2.js:28:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: t[0].involvesToken is not a function
    at new t (/usr/src/app/node_modules/@uniswap/sdk/dist/sdk.cjs.production.min.js:1:15658)
    at SdkV2.getPrice (/usr/src/app/node_modules/@giveth/monoswap/dist/src/sdk/sdkV2.js:82:23)
    at SdkV2.<anonymous> (/usr/src/app/node_modules/@giveth/monoswap/dist/src/sdk/sdkV2.js:150:33)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/@giveth/monoswap/dist/src/sdk/sdkV2.js:28:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: t[0].involvesToken is not a function
    at new t (/usr/src/app/node_modules/@uniswap/sdk/dist/sdk.cjs.production.min.js:1:15658)
    at SdkV2.getPrice (/usr/src/app/node_modules/@giveth/monoswap/dist/src/sdk/sdkV2.js:82:23)
    at SdkV2.<anonymous> (/usr/src/app/node_modules/@giveth/monoswap/dist/src/sdk/sdkV2.js:150:33)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/@giveth/monoswap/dist/src/sdk/sdkV2.js:28:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="getReserves()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at Logger.makeError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at Interface.decodeFunctionResult (/usr/src/app/node_modules/@ethersproject/abi/lib/interface.js:388:23)
    at Contract.<anonymous> (/usr/src/app/node_modules/@ethersproject/contracts/lib/index.js:395:56)
    at step (/usr/src/app/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/usr/src/app/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/usr/src/app/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'getReserves()',
  data: '0x',
  errorArgs: null,
  errorName: null,
  errorSignature: null,
  address: '0x6f5943aa2348942f35E527E573afa2E7514a62b5',
  args: [],
  transaction: {
    data: '0x0902f1ac',
    to: '0x6f5943aa2348942f35E527E573afa2E7514a62b5'
  }
}
TypeError: t[0].involvesToken is not a function
    at new t (/usr/src/app/node_modules/honeyswap-sdk/dist/honeyswap-sdk.cjs.production.min.js:1:15800)
    at SdkV2.getPrice (/usr/src/app/node_modules/@giveth/monoswap/dist/src/sdk/sdkV2.js:82:23)
    at SdkV2.<anonymous> (/usr/src/app/node_modules/@giveth/monoswap/dist/src/sdk/sdkV2.js:150:33)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/@giveth/monoswap/dist/src/sdk/sdkV2.js:28:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: t[0].involvesToken is not a function
    at new t (/usr/src/app/node_modules/honeyswap-sdk/dist/honeyswap-sdk.cjs.production.min.js:1:15800)
    at SdkV2.getPrice (/usr/src/app/node_modules/@giveth/monoswap/dist/src/sdk/sdkV2.js:82:23)
    at SdkV2.<anonymous> (/usr/src/app/node_modules/@giveth/monoswap/dist/src/sdk/sdkV2.js:150:33)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/@giveth/monoswap/dist/src/sdk/sdkV2.js:28:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: t[0].involvesToken is not a function
    at new t (/usr/src/app/node_modules/honeyswap-sdk/dist/honeyswap-sdk.cjs.production.min.js:1:15800)
    at SdkV2.getPrice (/usr/src/app/node_modules/@giveth/monoswap/dist/src/sdk/sdkV2.js:82:23)
    at SdkV2.<anonymous> (/usr/src/app/node_modules/@giveth/monoswap/dist/src/sdk/sdkV2.js:150:33)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/@giveth/monoswap/dist/src/sdk/sdkV2.js:28:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: t[0].involvesToken is not a function
    at new t (/usr/src/app/node_modules/honeyswap-sdk/dist/honeyswap-sdk.cjs.production.min.js:1:15800)
    at SdkV2.getPrice (/usr/src/app/node_modules/@giveth/monoswap/dist/src/sdk/sdkV2.js:82:23)
    at SdkV2.<anonymous> (/usr/src/app/node_modules/@giveth/monoswap/dist/src/sdk/sdkV2.js:150:33)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/@giveth/monoswap/dist/src/sdk/sdkV2.js:28:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by mohammadranjbarz** [comment]
@CarlosQ96  @mateodaza  
It seems it's a problem with monoswap package, can you look at it?

**Comment by divine-comedian** [comment]
Did anyone pick this up @CarlosQ96 @mateodaza ?

**Comment by mateodaza** [comment]
> Did anyone pick this up @CarlosQ96 @mateodaza ? 

I updated the package and it seemed to have fixed it, no @CarlosQ96 ?

**Comment by CarlosQ96** [comment]
@mateodaza @divine-comedian this was upgraded on staging and master. The problem has been solved.

**Comment by divine-comedian** [comment]
Thanks man, closing this then
